### ISSUE TITLE
"Warning" error, right after install on vanilla WordPress

### ISSUE THREAD

**Issue by baktelraalis** [gordielachance/wp-soundsystem#126]
Hello Gordie,

I just found your amazing plugin tonight, which seems very inspirating for a personal project, but I have some trouble right after installing it on a vanilla WordPress, seeing those error messages multiple times: 

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-class.php on line 124`

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-class.php on line 126`

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-class.php on line 127`

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-link-class.php on line 67`

`Warning: Cannot modify header information - headers already sent by (output started at /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-class.php:124) in /home/X/public_html/ps42/wp-admin/includes/misc.php on line 1196`

`Warning: Cannot modify header information - headers already sent by (output started at /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-class.php:124) in /home/X/public_html/ps42/wp-includes/pluggable.php on line 1251`

`Warning: Cannot modify header information - headers already sent by (output started at /home/X/public_html/ps42/wp-content/plugins/wp-soundsystem/classes/wpsstm-track-class.php:124) in /home/X/public_html/ps42/wp-includes/pluggable.php on line 1254`

I tried to pass my PHP on 5.6 and 7.3, while it's creating big troubles on 5.6, it's better on 7.3 but I'm seeing all those error messages at the backend page top which are making the plugin not usable.

I will be glad to make a follow up on the situation with you in order to help to optimize the plugin and get rid of this message.

Thanks in advance.

**Comment by gordielachance** [comment]
hi ! can you copy paste me your log so I can see which lines exactly are
affected ?
It's weird because I got not a single error on my own setup...
Thanks

Le dim. 1 sept. 2019 à 01:26, Bakt El Raalis <notifications@github.com> a
écrit :

**Comment by gordielachance** [comment]
indeed, an error fired by PHP 7.3 due to a small code error.
now fixed.
