### ISSUE TITLE
CSS opacity and filters

### ISSUE THREAD

**Issue by kimberley1111** [gordielachance/wp-soundsystem#28]
I see a lot of opacity and filters in the CSS and please remove them :) It's nice when you need it, but don't use it to make something fancy. The look is not your job ;) the script is awesome and unique!

A lot of themes get a conflict with a CSS like you make. Designers want to make his own CSS and don't want to use **!important** CSS override. 

remove
filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=50);
  opacity: 0.5;

**Comment by gordielachance** [comment]
It is automatically generated by the compass files (.scss).
In a further version, i'll put design in a separate file that you will be able to dequeue.
