### ISSUE TITLE
Request some feature

### ISSUE THREAD

**Issue by azbotboyz** [gordielachance/wp-soundsystem#30]
- I thing you shoul try this player https://github.com/MoePlayer/APlayer it  beautiful, support many fomat, support add image on player for each audio, and specialy is support play lyrict
- provide more source video ex: zippyshare, googledrive because as i know souncloud has stoped provide api https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform and spotify doesnt provide their service in  some country 
-possibly to fill the artis, track, album information like image, description, name v.v with out musicbrainz id

**Comment by gordielachance** [comment]
From what I see, APlayer is not able to play streams from Soundcloud/Youtube/..., is it ?  The [current library](http://www.mediaelementjs.com/) can...
